codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 0.4
        if_not_found: success

ignore:
  - "v2_shapefile/**" # ignore WIP
  - "testing_files/**" # ignore testing files
  - "updateCsv*" # ignore scripts to update CSV
