name: pydar
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14  # minimum support 3.10, maximum support 3.13
  - beautifulsoup4
  - pandas
  - pdr
  - pre-commit # pre-commit hooks
  - pyproj
  - pytest      # dev: testing
  - pytest-cov  # dev: codecov reports
  - pre-commit  # dev: pre-commit hooks
  - rasterio
  - urllib3
  - pip
  - pip:
    - matplotlib # avoid warning "QApplication: invalid style override passed, ignoring it."
