name: update-dynamic-csv-data-files

on:
  schedule:
    - cron: '0 0 1 * *' # “At 00:00 on day-of-month 1”

jobs:
  build:

    runs-on: ubuntu-20.04 # specifically calls the version number instead of lastest to work on 'act'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    - name: pip install
      run: |
        pip install pydar

    - name: execute python update_csv.py script # web scrap to get any new changes
      working-directory: pydar
      run: |
        python update_csv.py

    - name: Find changed files
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files

    - name: Commit and push if files have been changed
      run: |-
        git config user.name "GitHub Action"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit --allow-empty -m "Github Actions: update csv scripts (${timestamp}), change files = ${{ steps.verify-changed-files.outputs.files_changed }}"
        git push


